### ISSUE TITLE
FAILED! => {"msg": "Authentication failed."}

### ISSUE THREAD

**Issue by wayneshow** [HuaweiSwitch/CloudEngine-Ansible#55]
when I use ce_vxlan_tunnel (set the VNI and mapped to the BD),  report error：
FAILED! => {"msg": "Authentication failed."}

**Comment by yuandongx** [comment]
Do you make the same mistake with other modules? And use ce_command ,ce_vlan?
Maybe the user password verification is wrong.You can try to connect manually.
i.e. shell command:  ssh -p 22 root@10.1.1.1 or ssh -p 22 root@10.1.1.1 -s netconf
If the connection is on, it is wrong with playbook to connect.
Please note that user login device can not give prompt password modification information.Because ansible will not handle this situation
